//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC_M2_V2._00.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SC_M2_V2._00.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The camera is on.
        /// </summary>
        internal static string CamConnected {
            get {
                return ResourceManager.GetString("CamConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting the camera.
        /// </summary>
        internal static string CamConnecting {
            get {
                return ResourceManager.GetString("CamConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap camera_logo {
            get {
                object obj = ResourceManager.GetObject("camera logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 720.
        /// </summary>
        internal static string FrameHeight {
            get {
                return ResourceManager.GetString("FrameHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1280.
        /// </summary>
        internal static string FrameWidth {
            get {
                return ResourceManager.GetString("FrameWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./System/Images.
        /// </summary>
        internal static string Path_Image {
            get {
                return ResourceManager.GetString("Path_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./System/Image_classification.
        /// </summary>
        internal static string Path_ImageClassification {
            get {
                return ResourceManager.GetString("Path_ImageClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\CPush\SC-M2\ImageClassification\bin\Debug\net7.0.
        /// </summary>
        internal static string Path_ImageClassificationTemp {
            get {
                return ResourceManager.GetString("Path_ImageClassificationTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./System/log.
        /// </summary>
        internal static string Path_log {
            get {
                return ResourceManager.GetString("Path_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./System.
        /// </summary>
        internal static string Path_System {
            get {
                return ResourceManager.GetString("Path_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./System/temp.
        /// </summary>
        internal static string Path_System_Temp {
            get {
                return ResourceManager.GetString("Path_System_Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 731TMC ECU INSPECTION SOFTWARE V2.10.
        /// </summary>
        internal static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input employee ID.
        /// </summary>
        internal static string STATUS_PROCES_10 {
            get {
                return ResourceManager.GetString("STATUS_PROCES_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select driver of camera!.
        /// </summary>
        internal static string STATUS_PROCES_11 {
            get {
                return ResourceManager.GetString("STATUS_PROCES_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera disconnected..
        /// </summary>
        internal static string STATUS_PROCES_12 {
            get {
                return ResourceManager.GetString("STATUS_PROCES_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System is processing.
        /// </summary>
        internal static string STATUS_PROCES_13 {
            get {
                return ResourceManager.GetString("STATUS_PROCES_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera connected..
        /// </summary>
        internal static string STATUS_PROCES_CAMERA_CON {
            get {
                return ResourceManager.GetString("STATUS_PROCES_CAMERA_CON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string STATUS_PROCES_CONNECTING {
            get {
                return ResourceManager.GetString("STATUS_PROCES_CONNECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera not connected.
        /// </summary>
        internal static string STATUS_PROCES_DIS {
            get {
                return ResourceManager.GetString("STATUS_PROCES_DIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NG.
        /// </summary>
        internal static string STATUS_PROCES_NG {
            get {
                return ResourceManager.GetString("STATUS_PROCES_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image not match.
        /// </summary>
        internal static string STATUS_PROCES_NOT_MATCH {
            get {
                return ResourceManager.GetString("STATUS_PROCES_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string STATUS_PROCES_OK {
            get {
                return ResourceManager.GetString("STATUS_PROCES_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert data employee.
        /// </summary>
        internal static string STATUS_PROCESS_1 {
            get {
                return ResourceManager.GetString("STATUS_PROCESS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select driver camera.
        /// </summary>
        internal static string STATUS_PROCESS_2 {
            get {
                return ResourceManager.GetString("STATUS_PROCESS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select COM port or baud.
        /// </summary>
        internal static string STATUS_PROCESS_3 {
            get {
                return ResourceManager.GetString("STATUS_PROCESS_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open the camera.
        /// </summary>
        internal static string STATUS_PROCESS_4 {
            get {
                return ResourceManager.GetString("STATUS_PROCESS_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for detection.
        /// </summary>
        internal static string STATUS_PROCESS_5 {
            get {
                return ResourceManager.GetString("STATUS_PROCESS_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR Read Data....
        /// </summary>
        internal static string STATUS_PROCESS_6 {
            get {
                return ResourceManager.GetString("STATUS_PROCESS_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera are opening..
        /// </summary>
        internal static string STATUS_PROCESS_7 {
            get {
                return ResourceManager.GetString("STATUS_PROCESS_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Connected.
        /// </summary>
        internal static string STATUS_PROCESS_8 {
            get {
                return ResourceManager.GetString("STATUS_PROCESS_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Disconnect.
        /// </summary>
        internal static string STATUS_PROCESS_9 {
            get {
                return ResourceManager.GetString("STATUS_PROCESS_9", resourceCulture);
            }
        }
    }
}
